version: "3.8"

services:
  backend:
    build: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./server/.env

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src
    env_file:
      - ./client/.env
    stdin_open: true
    tty: true
    depends_on:
      - backend
